cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, plus_cart_item, minus_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('plus_cart_item/<slug:item_slug>/', plus_cart_item, name='plus_cart_item'),
    path('minus_cart_item/<slug:item_slug>/', minus_cart_item, name='minus_cart_item'),
]

online_store_SportZone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('checkout/', include('orders.urls')),
    path('users/', include('users.urls')),
    path('', include('store.urls')),
    path('', include('django.contrib.auth.urls')),
    path('/favorites/', include('favs.urls')),
    path('manager/', include('manager_panel.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from .views import checkout, create_order, thank_you

app_name = 'checkout'

urlpatterns = [
    path('', checkout, name='checkout'),
    path('create-order/', create_order, name='create_order'),
    path('thank-you/<int:order_id>/', thank_you, name='thank_you'),
]

store/urls.py
from django.urls import path

from .views import item_details, store, tag_details, tag_list, filtered_by_tag

app_name = 'store'


urlpatterns = [
    path('', store, name='home'),
    path('categories/', tag_list, name='tag_list'),
    path('category-details/<slug:slug>/', tag_details, name='tag_details'),
    path('<slug:item_slug>/', item_details, name='item_details'),
    path('filtered_by_tag/<slug:slug>/', filtered_by_tag, name='filtered_by_tag'),

]

cart/models.py
from django.contrib.auth.models import User
from django.db import models

from store.models import Item


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='carts', verbose_name='Покупатель',)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания',)

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    @property
    def total_price(self):
        total_price = sum(item.total_price for item in self.items.all())
        return total_price

    def __str__(self):
        return f"Cart {self.id} for {self.user.username}"

    def clear(self):
        self.items.all().delete()


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items', verbose_name='Корзина')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество',)

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'

    @property
    def total_price(self):
        total_price = self.quantity * self.item.price
        return total_price

    def __str__(self):
        return f"{self.quantity} x {self.item.title}"

cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import csrf_exempt

from store.models import Item
from .models import Cart, CartItem


@login_required
def cart(request):
    """
    Представление для вывода всех объектов
    товаров корзины и самой корзины.
    """
    cart = Cart.objects.filter(user=request.user).first()

    if not cart:
        cart = Cart.objects.create(user=request.user)

    context = {
        'cart_items': CartItem.objects.filter(cart=cart),
        'cart': cart
    }

    return render(request, 'cart/cart.html', context)


@login_required
def add_to_cart(request, item_slug):
    """
    Представление для добавления товара в корзину
    либо увеличения его количества на 1.
    """
    item = get_object_or_404(Item, slug=item_slug)
    cart, _ = Cart.objects.get_or_create(user=request.user)

    cart_item, created = CartItem.objects.get_or_create(
        cart=cart,
        item=item
    )
    if not created:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('cart:cart')




@login_required
def delete_cart_item(request, item_slug):
    """
    Представление для удаления объекта товара в корзине.
    """
    cart_item = CartItem.objects.get(
        cart=Cart.objects.get(user=request.user),
        item=get_object_or_404(Item, slug=item_slug)
    )
    cart_item.delete()
    return redirect('cart:cart')


@login_required
def plus_cart_item(request, item_slug):
    cart_item = CartItem.objects.get(
        cart=Cart.objects.get(user=request.user),
        item=get_object_or_404(Item, slug=item_slug)
    )
    cart_item.quantity += 1
    cart_item.save()
    return redirect('cart:cart')

@login_required
def minus_cart_item(request, item_slug):
    cart_item = CartItem.objects.get(
        cart=Cart.objects.get(user=request.user),
        item=get_object_or_404(Item, slug=item_slug)
    )
    cart_item.quantity -= 1
    cart_item.save()
    return redirect('cart:cart')

templates/cart/cart.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "/css/cart.css"%}" />
{% endblock %}

{% block content %}
<h1>Корзина</h1>
{% if cart_items %}
    <section>
        <div class="table-wrapper">
            <table class="alt">
                <thead>
                <tr>
                    <th>Название</th>
                    <th>Количество</th>
                    <th>Цена</th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                    <tr>
                        <td><a href="{% url 'store:item_details' cart_item.item.slug %}">{{ cart_item.item.title }}</a></td>
                        <td>
                            <div class="count">
                                <a class="countPlus" href="{% url 'cart:minus_cart_item' cart_item.item.slug %}">-</a>
                                <div class="quantity">{{ cart_item.quantity }}</div>
                                <a class="countMinus" href="{% url 'cart:plus_cart_item' cart_item.item.slug %}">+</a>
                            </div>
                        </td>
                        <td class="cart-item-total-price" data-cart-item-id="{{ cart_item.id }}">{{ cart_item.total_price }}</td>
                        <td style="border: none; background-color: #ffffff;" align="center">
                            <a href="{% url 'cart:delete_cart_item' cart_item.item.slug %}">
                                <img src ="{% static "images/garbage.svg" %}" width="25" height="25" >
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="2"></td>
                    <td><u><b><span id="cart-total-price" data-cart-id="{{ cart.id }}">{{ cart.total_price }}</span></b></u></td>
                </tr>
                </tfoot>
            </table>
        </div>
    </section>
    <div style="text-align: justify;">
        <a href="{% url 'store:home' %}" style="float: left;" class="button">Продолжить покупки</a>
        <a href="{% url 'checkout:checkout' %}" style="float: right;" class="button">Оформить заказ</a>
    </div>
{% else %}
    <p>Ваша корзина пуста.</p>
{% endif %}
{% endblock %}