cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, plus_cart_item, minus_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('plus_cart_item/<slug:item_slug>/', plus_cart_item, name='plus_cart_item'),
    path('minus_cart_item/<slug:item_slug>/', minus_cart_item, name='minus_cart_item'),
]

manager_panel/urls.py
from django.urls import path

from . import views

app_name = 'manager'

urlpatterns = [
    path('addtag/', views.add_tag, name='add_tag'),
    path('taglist/', views.tag_list_manager, name='tag_list_manager'),
    path('delete/<slug:tag_slug>/', views.delete_tag, name='delete_tag'),
    path('itemlist/', views.item_list_manager, name='item_list_manager'),
    path('additem/', views.add_item, name='add_item'),
    path('deleteitem/<slug:item_slug>/', views.delete_item, name='delete_item'),
]

online_store_SportZone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('checkout/', include('orders.urls')),
    path('users/', include('users.urls')),
    path('', include('store.urls')),
    path('', include('django.contrib.auth.urls')),
    path('/favorites/', include('favs.urls')),
    path('manager/', include('manager_panel.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/panel/add_item.html
{% extends 'base.html' %}


{% block content %}
 <h2>Создание товара</h2>
 <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Создать</button>
 </form>
{% endblock %}%}

templates/panel/add_tag.html
{% extends 'base.html' %}


{% block content %}
    <h2>Новый тег</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>
{% endblock %}

templates/panel/items_list_manager.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div style="background-color: #999999; margin: auto;  border-radius: 25%">
        <a href="{% url 'manager:add_item' %}">
        <img src ="{% static "images/plus-solid.svg" %}" width="25" height="25" style="left: auto; border-radius: 50%" ></a>
    </div>
    <a href="{% url 'manager:tag_list_manager' %}">Список тегов</a>

<h2>Категории</h2>

    <table class="alt">
        <thead>
        <tr>
            <th>Название</th>
        </tr>
        </thead>
        <tbody>
        <hr>
        {% for item in items %}
            <tr>
                <td>
                    {{ item.title }}
                </td>
                 <td>
                    {{ item.description }}
                </td>
                 <td>
                    {{ item.old_price }}
                </td>
                 <td>
                    {{ item.price }}
                </td>
                 <td>
                    {{ item.tag }}
                </td>
                <td style="border: none; background-color: #ffffff;" align="center">
                    <a href="{% url 'manager:delete_item' item.slug %}">
                        <img src ="{% static "images/garbage.svg" %}" width="25" height="25" ></a>
                </td>
                <td style="border: none; background-color: #ffffff;" align="center">
{#                    <a href="{% url 'manager:update_tag' cart_item.item.slug %}">#}
{#                        <img src ="{% static "images/pen-solid.svg" %}" width="25" height="25" ></a>#}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock%}

templates/panel/tag_list_manager.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div style="background-color: #999999; margin: auto;  border-radius: 25%">
        <a href="{% url 'manager:add_tag' %}">
        <img src ="{% static "images/plus-solid.svg" %}" width="25" height="25" style="left: auto; border-radius: 50%" ></a>
         </div>
        <a href="{% url 'manager:item_list_manager' %}">Список товаров</a>

<h2>Категории</h2>

    <table class="alt">
        <thead>
{#        <tr>#}
{#            <th>Название</th>#}
{#        </tr>#}
        </thead>
        <tbody>
        <hr>
        {% for tag in tags %}
            <tr>
                <td>
                    {{ tag.name }}
                </td>

                <td style="border: none; background-color: #ffffff;" align="center">
                    <a href="{% url 'manager:delete_tag' tag.slug %}">
                        <img src ="{% static "images/garbage.svg" %}" width="25" height="25" ></a>
                </td>
                <td style="border: none; background-color: #ffffff;" align="center">
{#                    <a href="{% url 'manager:update_tag' cart_item.item.slug %}">#}
{#                        <img src ="{% static "images/pen-solid.svg" %}" width="25" height="25" ></a>#}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}