cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, plus_cart_item, minus_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('plus_cart_item/<slug:item_slug>/', plus_cart_item, name='plus_cart_item'),
    path('minus_cart_item/<slug:item_slug>/', minus_cart_item, name='minus_cart_item'),
]

favs/urls.py
from django.urls import path

from .views import favorites, add_to_favorites, delete_favorite_item

app_name = 'favs'

urlpatterns = [
    path('', favorites, name='favorites'),
    path('add/<slug:item_slug>/', add_to_favorites, name='add_to_favorites'),
    path('delete/<slug:item_slug>/', delete_favorite_item, name='delete_favorite_item'),
    # path('update_cart_item/', update_cart_item, name='update_cart_item'),
]

online_store_SportZone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('checkout/', include('orders.urls')),
    path('users/', include('users.urls')),
    path('', include('store.urls')),
    path('', include('django.contrib.auth.urls')),
    path('/favorites/', include('favs.urls')),
    path('manager/', include('manager_panel.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from .views import item_details, store, tag_details, tag_list, filtered_by_tag

app_name = 'store'


urlpatterns = [
    path('', store, name='home'),
    path('categories/', tag_list, name='tag_list'),
    path('category-details/<slug:slug>/', tag_details, name='tag_details'),
    path('<slug:item_slug>/', item_details, name='item_details'),
    path('filtered_by_tag/<slug:slug>/', filtered_by_tag, name='filtered_by_tag'),

]

store/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from taggit.managers import TaggableManager
from taggit.models import GenericTaggedItemBase, TagBase


class ItemTag(TagBase):
    class Meta:
        verbose_name = _("Категория")
        verbose_name_plural = _("Категории")


class TaggedItem(GenericTaggedItemBase):
    tag = models.ForeignKey(ItemTag, on_delete=models.CASCADE, related_name="items", verbose_name='Категория')


class Item(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    slug = models.SlugField(max_length=250)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    price = models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Новая цена')
    old_price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Старая цена', blank=True, null=True)
    image = models.ImageField(verbose_name='Изображение', upload_to='items/', blank=True)
    is_available = models.BooleanField(default=True, verbose_name='Доступно')
    is_sale = models.BooleanField(default=False, verbose_name='Скидка')
    tags = TaggableManager(through=TaggedItem, related_name="tagged_items", verbose_name='Категории',)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-price']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        indexes = [
            models.Index(fields=['title']),
        ]

store/forms.py
from django import forms
from .models import ItemTag
from .models import Item

class ItemTagForm(forms.ModelForm):
    class Meta:
        model = ItemTag
        fields = ['name']


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['title', 'description', 'price', 'old_price', 'image', 'is_available', 'is_sale', 'tags']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'old_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'is_available': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'is_sale': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'tags': forms.TextInput(attrs={'class': 'form-control'}),
        }

store/views.py
import random

from django.shortcuts import get_object_or_404, render

from .models import Item, ItemTag
from .paginator import paginator


def store(request):
    items = Item.objects.filter(is_sale=True)
    random_items = random.sample(list(items), 3)
    context = {
        'page_obj': paginator(request, random_items, 6)
    }

    return render(request, 'store/main_page.html', context)



def item_details(request, item_slug):
    item = get_object_or_404(Item, slug=item_slug)
    context = {
        'item': item,
    }
    return render(request, 'store/item_details.html', context)


def tag_details(request, slug):
    tag = get_object_or_404(ItemTag, slug=slug)
    items = Item.objects.filter(tags__in=[tag])
    context = {
        'tag': tag,
        'page_obj': paginator(request, items, 3),
    }

    return render(request, 'store/tag_details.html', context)


def tag_list(request):
    tags = ItemTag.objects.all()
    items = Item.objects.all()
    context = {
        'tags': tags,
        'page_obj': paginator(request, items, 6),
    }
    return render(request, 'store/tag_list.html', context)


def filtered_by_tag(request, slug):
    tags = ItemTag.objects.all()
    tag = get_object_or_404(ItemTag, slug=slug)
    items = Item.objects.filter(tags__in=[tag])
    context = {
        'tags': tags,
        'tag': tag,
        'page_obj': paginator(request, items, 3),
    }

    return render(request, 'store/filtered.html', context)

templates/store/filtered.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    <h2>Список всех категорий</h2>
    <hr>
{% for tag in tags %}
    <a href="{% url 'store:filtered_by_tag' tag.slug %}"><b>{{ tag.name }}</b></a>
{% endfor %}
    <section class="sales">
<div class="salesContainer">
    {% for item in page_obj %}
    <article class="cart">
        <span class="image">
        {% if item.image %}
            <img src="{{ item.image.url }}" alt=""/>
        {% else %}
            <img src="{% static "images/pic01.jpg" %}" alt="" />
        {% endif %}
        </span>
        <a href="{% url 'store:item_details' item.slug %}">
            <div class="tag">
                <object>
                    {% for tag in item.tags.all %}
                        <a class="category" href="{% url 'store:tag_details' tag.slug %}" >{{ tag }}</a>
                        {% if not forloop.last %},{% endif %}
                    {% endfor %}
                </object><br />
            </div>
            <h2 class="cartTitle">{{ item.title }}</h2>
            <div class="content">
                <p class="sale">Скидка</p>
            </div>
            <div class="price">
                 {% if item.old_price %}
                     <p>Старая цена: {{ item.old_price }} рублей</p>
                     <p>Новая цена: {{ item.price }} рублей </p>
                {% else %}
                     <p>Цена: {{ item.price }} рублей </p>
                {% endif %}

            </div>
        </a>
    </article>
    {% endfor %}
</div>
</section>
{% endblock %}

templates/store/item_details.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% load static %}
    <div class="containerItem">
        <h2>{{ item.title }}</h2>
        <p>Товар принадлежит к категории
            {% for tag in item.tags.all %}
                <b><a href="{% url 'store:tag_details' tag.slug %}">{{ tag }}</a></b>
                {% if not forloop.last %},{% endif %}
            {% endfor %}
        </p>
        <div class="imgDescr" style="display: flex; justify-content: left">
            {% if item.image %}
                <span class="imageItem"><img src="{{ item.image.url }}" alt="" style="max-width: 300px; max-height: 300px;"/></span>
            {% else %}
                <span class="imageItem"><img src="{% static "images/pic14.jpg" %}" alt="" /></span>
            {% endif %}

            <div class="descriptionItem">
                <p>{{ item.description }}</p>
            </div>
        </div>
        <div class="priceInfo">
            {% if item.old_price %}
                <p>Старая цена: {{ item.old_price }} рублей</p>
                <p>Новая цена: {{ item.price }}  рублей </p>
            {% else %}
                <p>Цена: {{ item.price }} рублей </p>
            {% endif %}
        </div>
        <div class="buttons">
            <a href="{% url 'cart:add_to_cart' item.slug %}" class="button small" style="margin-top:10px;">
                Добавить в корзину</a>

            <a href="{% url 'favs:add_to_favorites' item.slug %}" class="button small" style="margin-top:10px;">
                Добавить в избранное</a>
        </div>
    </div>
{% endblock %} 

templates/store/main_page.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<section class="sales">
<div class="salesContainer">
    {% for item in page_obj %}
    <article class="cart">
        <span class="image">
        {% if item.image %}
            <img src="{{ item.image.url }}" alt=""/>
        {% else %}
            <img src="{% static "images/pic01.jpg" %}" alt="" />
        {% endif %}
        </span>
        <a href="{% url 'store:item_details' item.slug %}">
            <div class="tag">
                <object>
                    {% for tag in item.tags.all %}
                        <a class="category" href="{% url 'store:tag_details' tag.slug %}" >{{ tag }}</a>
                        {% if not forloop.last %},{% endif %}
                    {% endfor %}
                </object><br />
            </div>
            <h2 class="cartTitle">{{ item.title }}</h2>
            <div class="content">
                <p class="sale">Скидка</p>
            </div>
            <div class="price">
                 {% if item.old_price %}
                     <p>Старая цена: {{ item.old_price }} рублей</p>
                     <p>Новая цена: {{ item.price }} рублей </p>
                {% else %}
                     <p>Цена: {{ item.price }} рублей </p>
                {% endif %}

            </div>
        </a>
    </article>
    {% endfor %}
</div>
</section>
{% endblock %}

templates/store/tag_details.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    <h2>{{ tag.name }}</h2>
    Количество товаров:&ensp;{{ tag.items.count }}
    <p><a href="{% url 'store:tag_list'%}"><b>Все категории</b></a></p>
    <hr>
{% for item in page_obj %}
    <a href="{% url 'store:item_details' item.slug %}"><b>{{ item.title }}</b></a>
    <p><span class="image left">
        {% if item.image %}
            <img src="{{ item.image.url }}" alt="" style="max-width: 200px; max-height: 200px;"/>
        {% else %}
            <img src="{% static "images/pic01.jpg" %}" alt="" />
        {% endif %}
        <a href="{% url 'cart:add_to_cart' item.slug %}" class="button small" style="margin-top:10px;">
            Добавить в корзину</a>
        </span>
    <a href="{% url 'favs:add_to_favorites' item.slug %}" class="button small" style="margin-top:10px;">
            Добавить в избранное</a>
    </p>
    <p>{{ item.description }}</p>
    {% if item.old_price %}
        <p>Старая цена: <s>{{ item.old_price }} рублей</s>
        Новая цена: <b>{{ item.price }}</b> рублей </p>
    {% else %}
        <p>Цена: <b>{{ item.price }}</b> рублей </p>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}

{% endfor %}
{% endblock %} 

templates/store/tag_list.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    <h2>Список всех категорий</h2>
    <hr>
{% for tag in tags %}
    <a href="{% url 'store:filtered_by_tag' tag.slug %}"><b>{{ tag.name }}</b></a>
{% endfor %}
    <section class="sales">
<div class="salesContainer">
    {% for item in page_obj %}
    <article class="cart">
        <span class="image">
        {% if item.image %}
            <img src="{{ item.image.url }}" alt=""/>
        {% else %}
            <img src="{% static "images/pic01.jpg" %}" alt="" />
        {% endif %}
        </span>
        <a href="{% url 'store:item_details' item.slug %}">
            <div class="tag">
                <object>
                    {% for tag in item.tags.all %}
                        <a class="category" href="{% url 'store:tag_details' tag.slug %}" >{{ tag }}</a>
                        {% if not forloop.last %},{% endif %}
                    {% endfor %}
                </object><br />
            </div>
            <h2 class="cartTitle">{{ item.title }}</h2>
            <div class="content">
                <p class="sale">Скидка</p>
            </div>
            <div class="price">
                 {% if item.old_price %}
                     <p>Старая цена: {{ item.old_price }} рублей</p>
                     <p>Новая цена: {{ item.price }} рублей </p>
                {% else %}
                     <p>Цена: {{ item.price }} рублей </p>
                {% endif %}

            </div>
        </a>
    </article>
    {% endfor %}
</div>
</section>
{% endblock %}