cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, plus_cart_item, minus_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('plus_cart_item/<slug:item_slug>/', plus_cart_item, name='plus_cart_item'),
    path('minus_cart_item/<slug:item_slug>/', minus_cart_item, name='minus_cart_item'),
]

favs/urls.py
from django.urls import path

from .views import favorites, add_to_favorites, delete_favorite_item

app_name = 'favs'

urlpatterns = [
    path('', favorites, name='favorites'),
    path('add/<slug:item_slug>/', add_to_favorites, name='add_to_favorites'),
    path('delete/<slug:item_slug>/', delete_favorite_item, name='delete_favorite_item'),
    # path('update_cart_item/', update_cart_item, name='update_cart_item'),
]

manager_panel/urls.py
from django.urls import path

from . import views

app_name = 'manager'

urlpatterns = [
    path('addtag/', views.add_tag, name='add_tag'),
    path('taglist/', views.tag_list_manager, name='tag_list_manager'),
    path('delete/<slug:tag_slug>/', views.delete_tag, name='delete_tag'),
    path('itemlist/', views.item_list_manager, name='item_list_manager'),
    path('additem/', views.add_item, name='add_item'),
    path('deleteitem/<slug:item_slug>/', views.delete_item, name='delete_item'),
]

online_store_SportZone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('checkout/', include('orders.urls')),
    path('users/', include('users.urls')),
    path('', include('store.urls')),
    path('', include('django.contrib.auth.urls')),
    path('/favorites/', include('favs.urls')),
    path('manager/', include('manager_panel.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from .views import item_details, store, tag_details, tag_list, filtered_by_tag

app_name = 'store'


urlpatterns = [
    path('', store, name='home'),
    path('categories/', tag_list, name='tag_list'),
    path('category-details/<slug:slug>/', tag_details, name='tag_details'),
    path('<slug:item_slug>/', item_details, name='item_details'),
    path('filtered_by_tag/<slug:slug>/', filtered_by_tag, name='filtered_by_tag'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from django.urls import path

from .views import SignUp, profile, user_orders

app_name = 'users'

urlpatterns = [
    path('orders/', user_orders, name='user_orders'),
    path('profile/', profile, name='profile'),
    path('auth/logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('auth/signup/', SignUp.as_view(), name='signup'),
    path('auth/login/', LoginView.as_view(template_name='users/login.html'), name='login')

]

templates/components/footer.html
<footer id="footer">
        <section class="footerNav">
            <h2>Наши контакты</h2>
            <ul class="icons">
                <li><a href="https://t.me/" class="icon solid style2 fa-phone"><span class="label">Telegram</span></a></li>
                <li><a href="mailto:branch5567@mail.ru" class="icon solid style2 fa-envelope"><span class="label">Email</span></a></li>
            </ul>
        </section>
</footer>

templates/components/header.html
{% load static %}

<header id="header">
    <div class="inner">
        <!-- Logo -->
          <a href="{% url 'store:home' %}" class="logo">
              <div class="logoNav">
                  <span class="symbol"><img src="{% static "images/logo3.png" %}" alt="" /></span>
                  <span class="title">SportZone</span>
              </div>
          </a>
        <!-- Nav -->
        <div class="navigation">
            <a href="{% url 'store:tag_list' %}">Каталог</a>
            {% if request.user.is_superuser%}
            <a href="{% url 'manager:tag_list_manager' %}">Панель</a>
            {% endif %}
        </div>

        <div class="navIcons">
            <a href="{% url 'favs:favorites' %}">
                <img src ="{% static "images/heart-regular.svg" %}" width="40" height="40" ></a>

            <a href="{% url 'cart:cart' %}">
                <img src ="{% static "images/cart-shopping-solid.svg" %}" width="40" height="40" ></a>

            <div class="cartCounterContainer">
                {% if cart_item_count.total_cart_items != None %}
                    <a class="cartCounter"> {{ cart_item_count.total_cart_items }}</a>
                {% elif cart_item_count.total_cart_items == None %}
                    <a class="cartCounter"> 0 </a>

                {% endif %}
            </div>
            <a href="{% url 'users:profile' %}">
                <img src ="{% static "images/circle-user-solid.svg" %}" width="40" height="40" ></a>
        </div>
    </div>
</header>

templates/components/paginator.html
{% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}" class="button paginator">Prev</a>
{% else %}
  <a class="button paginator disabled">Prev</a>
{% endif %}
{% for i in page_obj.paginator.page_range %}
  {% if page_obj.number == i %}
    <a href="#" class="button paginator disabled">{{ i }}</a>
  {% else %}
    <a href="?page={{ i }}" class="button paginator">{{ i }}</a>
  {% endif %}
{% endfor %}
{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}" class="button paginator">Next</a>
{% else %}
  <a class="button paginator disabled">Next</a>
{% endif %}